# Generated by Django 2.2.4 on 2019-12-26 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20191224_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=256)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.Category')),
            ],
            options={
                'verbose_name': 'subcategory',
                'verbose_name_plural': 'subcategories',
            },
        ),
        migrations.RemoveField(
            model_name='xsubcategory',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='xcat',
        ),
        migrations.RemoveField(
            model_name='post',
            name='xsubcat',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.Subcategory'),
        ),
        migrations.DeleteModel(
            name='XCategory',
        ),
        migrations.DeleteModel(
            name='XSubcategory',
        ),
    ]
