# Generated by Django 2.2.4 on 2019-12-26 09:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0003_auto_20191226_1428'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Replies',
            new_name='Reply',
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name': 'reply', 'verbose_name_plural': 'replies'},
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='reply',
            new_name='reply_message',
        ),
    ]
