# Generated by Django 2.2.4 on 2020-01-02 09:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20191227_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2020, 1, 2, 9, 47, 15, 333141, tzinfo=utc), null=True),
        ),
    ]
