# Generated by Django 2.2.4 on 2020-01-02 10:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_auto_20200102_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2020, 1, 2, 10, 53, 14, 900692, tzinfo=utc), null=True),
        ),
    ]
