# Generated by Django 2.2.4 on 2020-01-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_auto_20200102_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
