# Generated by Django 2.2.4 on 2020-01-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_auto_20200102_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='timestamp',
            new_name='timestamp_st',
        ),
    ]
