# Generated by Django 2.2.4 on 2019-12-07 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commented_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Created at'),
        ),
    ]
