# Generated by Django 2.2.4 on 2020-01-06 10:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_auto_20200102_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='reply_message',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='commented_at',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='is_rejected',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='parent',
        ),
        migrations.AddField(
            model_name='reply',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social.Comment'),
        ),
        migrations.AddField(
            model_name='reply',
            name='replied_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
