# Generated by Django 2.2.4 on 2019-12-07 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_auto_20191207_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='replies',
        ),
    ]
