# Generated by Django 2.2.4 on 2020-01-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_auto_20200106_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['commented_at']},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['replied_at'], 'verbose_name': 'reply', 'verbose_name_plural': 'replies'},
        ),
    ]
