# Generated by Django 2.2.4 on 2020-01-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_auto_20200106_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friend',
            field=models.ManyToManyField(blank=True, null=True, related_name='_profile_friend_+', to='social.Profile'),
        ),
    ]
