# Generated by Django 2.2.4 on 2019-12-07 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_auto_20191207_0129'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
            ],
        ),
    ]
