# Generated by Django 2.2.4 on 2019-12-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='replies',
            name='reply',
            field=models.CharField(default=None, max_length=160),
            preserve_default=False,
        ),
    ]
