# Generated by Django 2.2.4 on 2020-01-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_auto_20200115_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='is_friend',
            field=models.BooleanField(default=False),
        ),
    ]
