# Generated by Django 2.2.4 on 2020-01-16 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0018_friendship_is_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
