# Generated by Django 2.2.4 on 2020-01-16 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0019_friendship_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='owner',
            new_name='request_from',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='friend',
            new_name='request_to',
        ),
    ]
