# Generated by Django 2.2.4 on 2019-12-07 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0019_auto_20191207_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
    ]
