# Generated by Django 2.2.4 on 2019-12-09 04:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0020_remove_comment_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=160)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_rejected', models.BooleanField(default=False)),
                ('commented_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created at')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='social.Comment')),
                ('parent_reply_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.Replies')),
            ],
        ),
    ]
