# Generated by Django 2.2.4 on 2019-12-09 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0021_replies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replies',
            old_name='parent_id',
            new_name='parent',
        ),
        migrations.RemoveField(
            model_name='replies',
            name='parent_reply_id',
        ),
        migrations.AddField(
            model_name='replies',
            name='parent_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.Replies'),
        ),
    ]
