# Generated by Django 2.2.4 on 2019-12-09 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0024_auto_20191209_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='replies',
            name='commented_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Created at'),
        ),
    ]
