# Generated by Django 2.2.4 on 2019-12-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0029_dislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('adventure', 'Adventure'), ('fitness', 'Fitness'), ('health', 'Health'), ('food', 'Food')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.CharField(max_length=500, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='replies',
            name='reply',
            field=models.CharField(max_length=500),
        ),
    ]
