# Generated by Django 2.2.4 on 2019-12-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0030_auto_20191218_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subcategory',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('adventure', 'Adventure'), ('fitness', 'Fitness'), ('health', 'Health'), ('food', 'Food'), ('sports', 'Sports')], max_length=256, null=True),
        ),
    ]
